### ISSUE TITLE
Expose Custom Posts Endpoint in GraphQL

### ISSUE THREAD

**Issue by samlogan** [distilagency/starward#14]

**Comment by AllanPooley** [comment]
References:

- https://github.com/birdbrain/peritas/blob/master/graphQL/queries/wpQueries.js
- https://github.com/distilagency/chalk_app/blob/master/data/schemas/wpSchema.js

Need to understand
- Custom Post Types
- Taxonomies
And implement both of these in a testing environment

Use:
https://generatewp.com/post-type/
https://generatewp.com/taxonomy/
