### ISSUE TITLE
Add ES6 polyfill for IE11

### ISSUE THREAD

**Issue by samlogan** [distilagency/starward#50]
https://github.com/distilagency/parkerville/pull/17/commits/739d3e9b691339e9cbf31d73011933efbc2bb394

**Comment by AllanPooley** [comment]
Added in https://github.com/distilagency/starward/pull/65

**Comment by AllanPooley** [comment]
Reopening - still encountering promise issues in IE11 despite using babel-polyfill (particularly with multipage sites, or at least react pages with page content that is completely reloaded)

**Comment by AllanPooley** [comment]
Fixed in https://github.com/distilagency/starward/pull/69
