### ISSUE TITLE
Potential loading reducer bug

### ISSUE THREAD

**Issue by falconmick** [distilagency/starward#53]
```
import {
  CREATE_REQUEST,
  REQUEST_SUCCESS,
  REQUEST_FAILURE
} from '../actions/types';

const INITIAL_STATE = false;

export default function (state = INITIAL_STATE, action) {
  switch (action.type) {
  case CREATE_REQUEST:
    return true;
  case REQUEST_SUCCESS:
  case REQUEST_FAILURE:
    return false;
  default:
    return state;
  }
}
```

If we change the route to one page that loads in 1 second, then before 1 second has passed we navigate to another page that takes 10 seconds to load then the state after 1 second would resolve to false (not loading) even though the router is still loading. 

Also I don't know if this part of state would be re-used by any other async requests, so later on we might have a situation where multiple request go out fast and some are slower than the first that comes back.

I have not been able to test this as I am still just getting everything running, however I believe that by reading the code that the above would be possible.

Possible fix would be to use a jobs in progress counter, that way as we got 1,2 or more concurrent async actions causing loading to need to be true, the values of 1,2 would resolve truthy and not break current code. Then once all of them resolve and we get back to 0, it would go falsey again.

That being said, changing the value in state to be named numberLaoding instead of loading would make it obvious to anyone consuming that the value they will receive is a number instead of a boolean.

**Comment by samlogan** [comment]
This is only used when requesting data server side using onUpdate in React Router. Each time the user navigates to a new page the `CREATE_REQUEST` action creator is called which updates the loading state back to true.
