### ISSUE TITLE
Upgrade to Webpack 2

### ISSUE THREAD

**Issue by falconmick** [distilagency/starward#63]
@samlogan I can see an upgrade to Webpack 2 being highly valuable as we could use tree shaking to reduce js file size by allot, there are probably allot of other reasons I just havn't made time to look into it enough yet. Also we should look into adding route based chunking while we are updating webpack (if we do). This way the user doesn't need to download the js for all of the junk on the other pages until they navigate there. React Boilerplate has this functionality.

If we do look into it, this could be useful https://webpack.js.org/guides/migrating/

**Comment by samlogan** [comment]
Yeah I agree. I will look into the migration this weekend
