### ISSUE TITLE
Upgrade to React Router v4

### ISSUE THREAD

**Issue by falconmick** [distilagency/starward#64]
We are currently running React Router v2. Only benefits I see from migrating is that if there are bugs we can get fixes as the version we are on is pretty dead.

https://gist.github.com/kennetpostigo/7eb7f30162253f995cd4371d85c1e196

The above is a guide/blog about migrating from v2 to v4, it looks like it's mostly renaming. But the benefit we get will be that if we want to have child routes we can do them separately as routes now simply are components, so the sub-routes can be defined in the component we use on the base route.

Edit:
there are also official docs:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

**Comment by samlogan** [comment]
Cool man, will roll this out with the Webpack update. Good work!

**Comment by samlogan** [comment]
@puravin can you help us with this, check that it integrates tightly with the fetch data calls?

**Comment by falconmick** [comment]
Should we leave this until after apollo potentially?

**Comment by falconmick** [comment]
Starting work on this
