### ISSUE TITLE
Enable preview functionality from the Wordpress admin area

### ISSUE THREAD

**Issue by samlogan** [distilagency/starward#66]
@AllanPooley can you please implement this as per the example I showed you

**Comment by AllanPooley** [comment]
On it today!

**Comment by AllanPooley** [comment]
More complicated than initially expected.
@puravin has implemented redirection of preview requests received by WP server to the React server, but at the moment we cannot retrieve ACF content from Post or Page objects using the WP REST API. We may need to investigating extending it to provide this functionality.
