### ISSUE TITLE
Create new way to figure out active nav item

### ISSUE THREAD

**Issue by falconmick** [distilagency/starward#76]
**Remove reliance on WP_URL for client side**

A benefit of this proxy is hiding the WP endpoint which is the most vulnerable part of our app. Unfortunately we are actively advertising it via having it in the source. Once  feature/formsubmit is complete it's only reliance on the client side will be inside of wpHelpers. It uses the WP_URL to split the nav away from it's active url string that we use to find out if it's the current nav item.

We need to replace getSlug from wpHelpers using probably the slug value that the nav item knows about and our current route.

**Comment by samlogan** [comment]
Done in #84
