### ISSUE TITLE
Add circuit breaker pattern

### ISSUE THREAD

**Issue by falconmick** [distilagency/starward#89]
If we were to ever have a starward site go live with billions of requests a day required the biggest issue we would face would be any non cached endpoints causing us to spam Wordpress and take it down.

So far we cache all WP calls, so this is not an issue, however if we have a bug or a 404, we would have to either cache the error/404 OR hit the API each time. Both of which suck!

Solution: Add a Circuit Breaker powered by redis (redis is kinda all or nothing, so I don't mind placing a weakness to failure on it) that way when an endpoint is having issues, we can automate the revival of that endpoint if/when the issue is resolved.

Input?

**Comment by samlogan** [comment]
Closing this for now to clean up issue log
