### ISSUE TITLE
Webpack 3 + code splitting

### ISSUE THREAD

**Issue by samlogan** [distilagency/starward#95]

**Comment by falconmick** [comment]
Might be worth considering using Webpack 4 as it was released a week ago.

https://medium.com/webpack/webpack-4-released-today-6cdb994702d4

Lots of perf stuff + easier config

**Comment by falconmick** [comment]
Whenever this is implemented, the following would also rock: https://github.com/Klathmon/imagemin-webpack-plugin

That way our non WP images can also be auto-optimised

**Comment by falconmick** [comment]
just upgraded RFF to webpack 4.5 and the process isn't too hard. I would recomend upgrading from 1-> 2, 2->3, 3->4 because there are a few gotchas and by doing so in steps its easier to google fixes, i.e. ExtractTextPlugin webpack 3 might mean somthing.
