### ISSUE TITLE
Change Script loading to defer

### ISSUE THREAD

**Issue by falconmick** [distilagency/starward#97]
https://bitsofco.de/async-vs-defer/

We have 3 script tags on our pages. 

1. Initial State
2. pollyfill
3. app code

If we were to add the defer attribute to these we would allow the page to load and render without blocking first paint (see article above)

To get the initial state to load defer'd we will need to save the contents of the script block into redis and make it avaiable from a /script/{hash} endpoint where hash is the hash of the script's data so that way we can store the hash'd script in redis and request it later.

Do note that we must ensure that the expiry and removal of the initial state script in redis MUST be tied to the lifespan of the page. If we remove the script from our cache and not the page, we will not have the data as the caching of the script won't run as the page was cached.

By doing the above we end up with 70-90% smaller data payload for initial page paint.

So just a tad of an improvement.

**Comment by falconmick** [comment]
- [ ] Pick a staging site and take initial readings before optimisation on a few benchmarking sites (namely Google Page Speed)

- [ ] Move initial state to redis API request

- [ ] change scripts to defer

- [ ] run benchmarks again

**Comment by falconmick** [comment]
I just did a test on this and 2,3 changing to defer is ok, but i wouldn't bother with caching Initial state into redis as theres too many edge cases that can cause confusing bugs.

**Comment by samlogan** [comment]
Added in #108
